version: '3'

services:
    opensim:

        image: opensim-opensim

        environment:
            - CONFIGKEY
            - CONFIG_NAME
            - EXTERNAL_HOSTNAME

        volumes:
            - ./config:/home/opensim/opensim/bin/config

        ports:
            - 8002:8002/tcp
            - 8002:8002/udp
            - 9000:9000/tcp
            - 9000:9000/udp
            - 9010:9010/tcp
            - 9010:9010/udp

        # restart: always
