
version: '3'

services:

    mysql:
        # MySql version 8 requires a bunch of new security stuff. Stay with v5.
        # image: mysql:5
        image: mariadb:latest
        # container_name: opensim-mysql
        environment:
            MYSQL_ROOT_PASSWORD:
        # Parameters added to invocation.
        # Default is to flush after every operation which slows Docker image down.
        # This flushes log once a second.
        command: --innodb_flush_log_at_trx_commit=2 --sync_binlog=0
        volumes:
            # NOTE: you must create this directory before starting the simulator
            # This mysql data directory can be placed anywhere
            - ~/mysql-data:/var/lib/mysql
        # restart: always

    opensim:
        depends_on:
            - mysql
        image: opensim-standalone
        environment:
            CONFIG_NAME:
            CONFIGKEY:
            EXTERNAL_HOSTNAME:
        ports:
            - 8002:8002/tcp
            - 8002:8002/udp
            - 9000:9000/tcp
            - 9000:9000/udp
            - 9010:9010/tcp
            - 9010:9010/udp
        links:
            - mysql:mysql
        # restart: always
