
version: '3'

services:

    opensim:
        image: opensim-herbal3d

        environment:
            CONFIG_NAME:
            CONFIGKEY:
            EXTERNAL_HOSTNAME:

        network_mode: "host"

        volumes:
            # overlay the OpenSimulator bin/config/ with external config/
            - ./config:/home/opensim/opensim/bin/config
            # Loden generated asset directory tree is stored externally
            - /home/basil/LodenAssets:/home/opensim/opensim/bin/LodenAssets
            # Linkage for local mysqld
            - /var/run/mysqld:/var/run/mysqld

        ports:
            - 8002:8002/tcp
            - 9000:9000/tcp
            - 9050:9050/udp
            - 9051:9051/tcp

        restart: unless-stopped
