version: '3'

services:
    opensim:

        image: opensim-herbal3d

        environment:
            - CONFIGKEY
            - CONFIG_NAME
            - EXTERNAL_HOSTNAME

        # If the configuration is outside of the container
        # volumes:
        #     - ./config:/home/opensim/opensim/bin/config

        ports:
            - 8002:8002/tcp
            - 8002:8002/udp
            - 9000:9000/tcp
            - 9000:9000/udp
            - 9050:9050/tcp
            - 9050:9050/udp
            - 11440-11449:11440-11449

        # restart: always
