
version: '3'

services:

    mysql:
        image: mariadb/server:latest
        # container_name: opensim-herbal3d-mysql
        environment:
            MYSQL_ROOT_PASSWORD:
        volumes:
            - ~/mysql-data:/var/lib/mysql
        # restart: always

    opensim:
        depends_on:
            - mysql
        image: opensim-herbal3d
        environment:
            CONFIG_NAME:
            CONFIGKEY:
            EXTERNAL_HOSTNAME:
        ports:
            - 8002:8002/tcp
            - 8002:8002/udp
            - 9000:9000/tcp
            - 9000:9000/udp
            - 9050:9050/tcp
            - 9050:9050/udp
            - 11440-11449:11440-11449
        links:
            - mysql:mysql
        # restart: always

    basiljs:
        image: basiljs-herbal3d
        ports:
            - 80:80
        # restart: always

